"""Backwards-compat tests against a frozen v1 SQLite fixture.

The fixture (``tests/fixtures/switching_v1.db``) was generated by
``scripts/build_test_fixture.py`` and represents the storage shape we
write today (Portfolio scalars + blobs, positions, closed_trades,
exit_tracks, skipped_signals, trade_memory, dropped_signals).

Every test in this file copies the fixture to a fresh tmp_path then loads
it via the **public** APIs (``Portfolio.load`` etc).  If a future code
change drops a column, renames a key, or otherwise breaks the load path,
these tests fail in CI before the change can merge — protecting the
trade history we've already collected.

When a schema change is **intentional**, regenerate the fixture
(``python scripts/build_test_fixture.py``) and update the assertions in
this file in the SAME commit, with a message explaining what changed.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from switching import storage


FIXTURE_PATH = Path(__file__).parent / "fixtures" / "switching_v1.db"


@pytest.fixture
def cache_dir(tmp_path):
    """Copy the frozen v1 db into a tmp cache dir and yield the paths."""
    assert FIXTURE_PATH.exists(), (
        f"fixture missing: {FIXTURE_PATH}.  Run "
        "`python scripts/build_test_fixture.py` to regenerate."
    )
    shutil.copy(FIXTURE_PATH, tmp_path / "switching.db")
    storage._reset_connection_cache()
    yield tmp_path
    storage._reset_connection_cache()


def _us_path(cache_dir):  return cache_dir / "paper_portfolio.json"
def _uk_path(cache_dir):  return cache_dir / "uk_portfolio.json"
def _t212_path(cache_dir): return cache_dir / "t212_portfolio.json"


# ---------------------------------------------------------------------------
# Portfolio (3 services, each via Portfolio.load)
# ---------------------------------------------------------------------------

def test_load_v1_us_portfolio_intact(cache_dir):
    from switching.paper_trader import Portfolio
    p = Portfolio.load(_us_path(cache_dir))
    # Cash + scalars
    assert p.cash == pytest.approx(18_432.55)
    assert p.max_position_pct == pytest.approx(0.015)
    assert p.max_positions == 50
    # Positions
    assert len(p.positions) == 2
    tickers = {pos.ticker for pos in p.positions}
    assert tickers == {"ACME", "RNDX"}
    acme = next(x for x in p.positions if x.ticker == "ACME")
    assert acme.detector == "guidance_raise"
    assert acme.entry_price == pytest.approx(40.0)
    assert acme.first_green is True
    assert len(acme.snapshots) == 1
    rndx = next(x for x in p.positions if x.ticker == "RNDX")
    assert rndx.peak_tracking is True
    # Closed trades — locks in the 3 different exit_reasons
    assert len(p.trades) == 3
    reasons = {t.exit_reason for t in p.trades}
    assert reasons == {"first_green", "stop_loss", "corporate_action"}
    # Severity column survived (added recently)
    assert all(t.severity is not None for t in p.trades)
    # Blobs
    assert len(p.seen_signals) == 3
    assert "OLD" in p.recently_sold
    # Cached prices restored
    assert p.cached_prices.get("ACME") == pytest.approx(42.1)


def test_load_v1_uk_portfolio_intact(cache_dir):
    from switching.paper_trader import Portfolio
    p = Portfolio.load(_uk_path(cache_dir))
    assert p.cash == pytest.approx(19_876.10)
    assert len(p.positions) == 1
    assert p.positions[0].ticker == "GAMA.L"
    assert p.positions[0].detector == "uk_director_dealing"
    assert len(p.trades) == 1
    assert p.trades[0].ticker == "VOD.L"


def test_load_v1_t212_portfolio_intact(cache_dir):
    from switching.paper_trader import Portfolio
    p = Portfolio.load(_t212_path(cache_dir))
    assert p.cash == pytest.approx(4_532.18)
    assert len(p.positions) == 1
    assert p.positions[0].ticker == "NVDA"
    assert p.recently_sold.get("MSFT")  # ISO timestamp present


def test_pending_orders_field_loads_or_defaults_empty(cache_dir):
    """The pending_orders queue (added 2026-05-27) must round-trip; older
    fixtures with no entry must default to an empty dict, not crash."""
    from switching.paper_trader import Portfolio
    us = Portfolio.load(_us_path(cache_dir))
    # US has 1 queued signal in the fixture
    assert isinstance(us.pending_orders, dict)
    assert len(us.pending_orders) == 1
    queued_keys = list(us.pending_orders.keys())
    assert "LATE" in queued_keys[0]
    # UK and t212 have no queue — must default to empty
    uk = Portfolio.load(_uk_path(cache_dir))
    assert uk.pending_orders == {}


# ---------------------------------------------------------------------------
# Trackers (exit / skipped / trade_memory) — all US-scoped in the fixture
# ---------------------------------------------------------------------------

def test_load_v1_exit_tracker_intact(cache_dir):
    from switching.exit_tracker import ExitTracker
    et = ExitTracker.load(_us_path(cache_dir) / "..exit_tracker_unused", "us") \
        if False else ExitTracker.load(_us_path(cache_dir), "us")
    # 2 entries: 1 complete, 1 active
    assert len(et.tracked) == 2
    complete = [t for t in et.tracked if t.tracking_complete]
    active   = [t for t in et.tracked if not t.tracking_complete]
    assert len(complete) == 1 and len(active) == 1
    assert complete[0].ticker == "DONE"
    assert active[0].ticker == "TRACK"


def test_load_v1_skipped_tracker_intact(cache_dir):
    from switching.skipped_tracker import SkippedTracker
    st = SkippedTracker.load(_us_path(cache_dir), "us")
    assert len(st.skipped) == 2
    reasons = {s.skip_reason for s in st.skipped}
    assert reasons == {"max_positions", "insufficient_cash"}


def test_load_v1_trade_memory_intact(cache_dir):
    from switching.trade_memory import load_memory
    mem = load_memory(_us_path(cache_dir), "us")
    # Two detector/tier rows expected
    assert "guidance_raise:premium" in mem
    assert mem["guidance_raise:premium"]["trades"] == 12
    assert mem["guidance_raise:premium"]["wins"] == 8


def test_load_v1_dropped_signals_intact(cache_dir):
    from switching import detection_funnel
    drops = detection_funnel.load_drops(_us_path(cache_dir), limit=100)
    # 3 entries across us + t212
    assert len(drops) == 3
    reasons = {d["reason"] for d in drops}
    assert "no_ticker" in reasons
    assert "price_unavailable" in reasons
    assert any(r.startswith("t212_rejected:") for r in reasons)


# ---------------------------------------------------------------------------
# Round-trip: load → save → reload yields identical counts + key fields
# ---------------------------------------------------------------------------

def test_load_save_reload_us_no_data_loss(cache_dir):
    """The single biggest regression risk: save() drops rows on write back."""
    from switching.paper_trader import Portfolio
    before = Portfolio.load(_us_path(cache_dir))
    before.save(_us_path(cache_dir))                # no mutation — pure round-trip
    storage._reset_connection_cache()
    after = Portfolio.load(_us_path(cache_dir))

    assert len(after.positions) == len(before.positions)
    assert len(after.trades) == len(before.trades)
    assert after.cash == pytest.approx(before.cash)
    assert sorted(after.seen_signals) == sorted(before.seen_signals)
    assert after.recently_sold == before.recently_sold
    assert after.pending_orders == before.pending_orders
    # Severity field — if a future refactor drops it, this fails loud
    for b, a in zip(before.trades, after.trades):
        assert a.ticker == b.ticker
        assert a.exit_reason == b.exit_reason
        assert a.severity == b.severity


def test_load_save_reload_uk_no_data_loss(cache_dir):
    from switching.paper_trader import Portfolio
    before = Portfolio.load(_uk_path(cache_dir))
    before.save(_uk_path(cache_dir))
    storage._reset_connection_cache()
    after = Portfolio.load(_uk_path(cache_dir))
    assert len(after.positions) == len(before.positions) == 1
    assert len(after.trades) == len(before.trades) == 1
    assert after.positions[0].ticker == "GAMA.L"


def test_services_remain_isolated_after_save(cache_dir):
    """Save on one service must NOT touch another service's rows."""
    from switching.paper_trader import Portfolio
    uk_before = Portfolio.load(_uk_path(cache_dir))
    uk_n_pos, uk_n_trades = len(uk_before.positions), len(uk_before.trades)
    # Mutate + save US
    us = Portfolio.load(_us_path(cache_dir))
    us.cash += 100.0
    us.save(_us_path(cache_dir))
    storage._reset_connection_cache()
    # UK rows unchanged
    uk_after = Portfolio.load(_uk_path(cache_dir))
    assert len(uk_after.positions) == uk_n_pos
    assert len(uk_after.trades) == uk_n_trades
    assert uk_after.cash == pytest.approx(uk_before.cash)
